# This is a basic workflow to help you get started with Actions

name: Reorder

on:
  workflow_dispatch:

jobs:
  run:
    name: reorder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Delete existing reorder branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: reorder
          soft_fail: true
      - name: Create reorder branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'reorder'
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Reorder conferences
        run: npm run reorder-confs
      - name: Reorder valid locations
        run: npm run updateValidLocations
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Confs.tech Reorder Bot
          author_email: cgrail@users.noreply.github.com
          message: 'Reorder conferences'
          add: "['*.json']"